apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  rmq_default_user: {{ .Values.rmq_default_user | default "guest" | b64enc }}
  rmq_default_pass: {{ .Values.rmq_default_pass | default "guest" | b64enc }}