{
 "title": "Search Engine / UI",
 "tags": [
  "SE",
  "UI"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "DS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(web_pages_served{component=\"ui\"}, kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(web_pages_served{component=\"ui\", kubernetes_namespace=\"$namespace\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Web pages served",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(web_pages_served{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Web page generation histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(web_page_gen_time_bucket{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", component=\"ui\", pod=~\"$pod\"} |= ``"
    }
   ]
  }
 ]
}